# Feature Selection Analysis for XGBoost

In [1]:
import pandas as pd

from pathlib import Path
import pandas as pd
import sys

sys.path.insert(0, "../../")
from geometric_extraction_helper import ALL_FEATURE_KEYS
from models_helper import ModelTrainer
from dataviz_helper import plot_feature_selection_curve

In [2]:
# get the data
DATA_DIR = "../../3_data_curation_enrichement/3_9_split dataset to datasets and remove rare classes"

df_train = pd.read_parquet(Path(DATA_DIR) / "dataset_train_rare_classes_removed.parquet")
df_train_over = pd.read_parquet(Path(DATA_DIR) / "dataset_train_rare_classes_removed_oversampled.parquet")
df_val   = pd.read_parquet(Path(DATA_DIR) / "dataset_validation_rare_classes_removed.parquet")

df_train.head()

,aabb_min_x,aabb_min_y,aabb_min_z,aabb_max_x,aabb_max_y,aabb_max_z,aabb_len_x,aabb_len_y,aabb_len_z,aabb_ratio_z_x,...,label_ifc_entity,label_predefined_type,label_is_external,label_load_bearing,minor_label_unter_terrain,minor_label_konstruktionsergaenzung,minor_label_deckbelag,minor_label_bekleidung,minor_label_aussenliegendes_bauteil,minor_label_sonnenschutz
0,0.000000,0.00,0.0,2.260000,2.310003,0.85,2.260000,2.310003,0.85,0.376106,...,IfcSpace,GFA,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,0.000000,0.00,0.0,2.260000,2.310003,0.85,2.260000,2.310003,0.85,0.376106,...,IfcSpace,GFA,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,-0.752578,0.00,0.0,9.893693,14.360000,2.82,10.646271,14.360000,2.82,0.264881,...,IfcSpace,GFA,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,0.000000,-1.85,0.0,10.646270,12.510000,2.82,10.646270,14.360000,2.82,0.264882,...,IfcSpace,GFA,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,-0.158796,0.00,0.0,9.394583,9.845000,0.24,9.553379,9.845000,0.24,0.025122,...,IfcSpace,GFA,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [3]:
# split features and labels
label_cols = [c for c in df_train.columns if c.startswith("label_")]

X_train_over = df_train_over[ALL_FEATURE_KEYS]
y_train_over = df_train_over[label_cols]
X_val   = df_val[ALL_FEATURE_KEYS]
y_val   = df_val[label_cols]

print(f"Train (oversampled): {len(X_train_over)}, Val: {len(X_val)}")
print(f"Labels: {label_cols}")

Train (oversampled): 28756, Val: 8458
Labels: ['label_ifc_entity', 'label_predefined_type', 'label_is_external', 'label_load_bearing']

## 1. Read Feature Importance ranking

In [4]:
fi_df = pd.read_json("../4_2_train advanced ML models/feature_importance_xgboost.json", orient="records")
fi_df

                      feature  importance
0            geom_layer_count    0.095794
1      topo_unique_edge_count    0.089707
2                   mat_belag    0.071762
3                    mat_gips    0.056177
4   topo_euler_characteristic    0.047501
..                        ...         ...
68                 geom_z_max    0.000000
69                 mat_mörtel    0.000000
70                   mat_putz    0.000000
71                 geom_z_min    0.000000
72               mat_foamglas    0.000000

[73 rows x 2 columns]

## 2. Incremental feature selection loop

In [17]:
# loop through features in order of importance and evaluate model performance with increasing number of features
ordered_features = fi_df["feature"].tolist()
loop_results = []

for n in range(1, len(ordered_features) + 1):
    features_subset = ordered_features[:n]
    model = ModelTrainer("xgboost", label_cols)
    model.fit(X_train_over[features_subset], y_train_over)

    metrics_df = model.evaluate(X_val[features_subset], y_val)
    score = metrics_df.loc["mean", "f1_macro"]

    print(f"{n:2d} Features | Last Feature: {ordered_features[n-1]:35s} | F1-macro: {score:.4f}")
    loop_results.append({"n_features": n, "last_feature_added": ordered_features[n - 1], "f1_macro": score})

# save the loop results to a csv file
loop_df = pd.DataFrame(loop_results)
loop_df.to_csv("feature_selection_results_xgboost.csv", index=False)
loop_df

 1 Features | Last Feature: geom_layer_count                    | F1-macro: 0.3796
 2 Features | Last Feature: topo_unique_edge_count              | F1-macro: 0.4801
 3 Features | Last Feature: mat_belag                           | F1-macro: 0.4890
 4 Features | Last Feature: mat_gips                            | F1-macro: 0.5092
 5 Features | Last Feature: topo_euler_characteristic           | F1-macro: 0.5600
 6 Features | Last Feature: mat_kies                            | F1-macro: 0.5588
 7 Features | Last Feature: mat_beton                           | F1-macro: 0.5591
 8 Features | Last Feature: aabb_ratio_x_y                      | F1-macro: 0.5984
 9 Features | Last Feature: geom_ratio_area_vol                 | F1-macro: 0.6228
10 Features | Last Feature: mat_zement                          | F1-macro: 0.6175
11 Features | Last Feature: aabb_len_x                          | F1-macro: 0.6432
12 Features | Last Feature: mat_metall                          | F1-macro: 0.6359
13 Features | Last Feature: mat_bekleidung                      | F1-macro: 0.6451
14 Features | Last Feature: mat_backstein                       | F1-macro: 0.6363
15 Features | Last Feature: mat_kunststein                      | F1-macro: 0.6388
16 Features | Last Feature: aabb_len_y                          | F1-macro: 0.6631
17 Features | Last Feature: geom_compactness                    | F1-macro: 0.6673
18 Features | Last Feature: aabb_len_z                          | F1-macro: 0.6711
19 Features | Last Feature: aabb_max_z                          | F1-macro: 0.6639
20 Features | Last Feature: aabb_ratio_z_y                      | F1-macro: 0.6714
21 Features | Last Feature: tfbb_extent_2                       | F1-macro: 0.6810
22 Features | Last Feature: mat_aluminium                       | F1-macro: 0.6807
23 Features | Last Feature: tfbb_ratio_12                       | F1-macro: 0.6826
24 Features | Last Feature: aabb_max_x                          | F1-macro: 0.6775
25 Features | Last Feature: aabb_ratio_z_x                      | F1-macro: 0.6755
26 Features | Last Feature: topo_connected_components           | F1-macro: 0.6714
27 Features | Last Feature: topo_avg_face_area                  | F1-macro: 0.6869
28 Features | Last Feature: topo_face_count                     | F1-macro: 0.6878
29 Features | Last Feature: mat_werkstoff                       | F1-macro: 0.6861
30 Features | Last Feature: topo_vertex_edge_ratio              | F1-macro: 0.6862
31 Features | Last Feature: tfbb_extent_1                       | F1-macro: 0.6829
32 Features | Last Feature: mat_allgemein                       | F1-macro: 0.6849
33 Features | Last Feature: topo_vertex_count                   | F1-macro: 0.6899
34 Features | Last Feature: tfbb_extent_0                       | F1-macro: 0.6881
35 Features | Last Feature: aabb_min_z                          | F1-macro: 0.7058
36 Features | Last Feature: geom_centroid_x                     | F1-macro: 0.7036
37 Features | Last Feature: geom_projected_area                 | F1-macro: 0.6970
38 Features | Last Feature: horizontal_elements_below           | F1-macro: 0.6946
39 Features | Last Feature: aabb_max_y                          | F1-macro: 0.7076
40 Features | Last Feature: mat_dämm                            | F1-macro: 0.7061
41 Features | Last Feature: tfbb_volume                         | F1-macro: 0.7095
42 Features | Last Feature: mat_stahl                           | F1-macro: 0.7099
43 Features | Last Feature: geom_surface_area                   | F1-macro: 0.7113
44 Features | Last Feature: horizontal_elements_above           | F1-macro: 0.7135
45 Features | Last Feature: geom_centroid_z                     | F1-macro: 0.7083
46 Features | Last Feature: topo_max_face_area                  | F1-macro: 0.7075
47 Features | Last Feature: tfbb_planarity                      | F1-macro: 0.7090
48 Features | Last Feature: geom_volume                         | F1-macro: 0.7058
49 Features | Last Feature: aabb_volume                         | F1-macro: 0.7028
50 Features | Last Feature: mat_holz                            | F1-macro: 0.6975
51 Features | Last Feature: topo_genus                          | F1-macro: 0.7091
52 Features | Last Feature: aabb_min_x                          | F1-macro: 0.7067
53 Features | Last Feature: aabb_min_y                          | F1-macro: 0.7056
54 Features | Last Feature: geom_centroid_y                     | F1-macro: 0.7105
55 Features | Last Feature: tfbb_sphericity                     | F1-macro: 0.7152
56 Features | Last Feature: tfbb_ratio_02                       | F1-macro: 0.7085
57 Features | Last Feature: tfbb_linearity                      | F1-macro: 0.7188
58 Features | Last Feature: tfbb_primary_ax_z                   | F1-macro: 0.7123
59 Features | Last Feature: mat_keramik                         | F1-macro: 0.7111
60 Features | Last Feature: mat_kalksandstein                   | F1-macro: 0.7116
61 Features | Last Feature: aabb_diagonal                       | F1-macro: 0.7140
62 Features | Last Feature: mat_glas                            | F1-macro: 0.7132
63 Features | Last Feature: tfbb_ratio_01                       | F1-macro: 0.7112
64 Features | Last Feature: tfbb_primary_ax_x                   | F1-macro: 0.7197
65 Features | Last Feature: tfbb_primary_ax_y                   | F1-macro: 0.7140
66 Features | Last Feature: mat_naturstein                      | F1-macro: 0.7166
67 Features | Last Feature: geom_z_range                        | F1-macro: 0.7166
68 Features | Last Feature: mat_kunststoff                      | F1-macro: 0.7166
69 Features | Last Feature: geom_z_max                          | F1-macro: 0.7166
70 Features | Last Feature: mat_mörtel                          | F1-macro: 0.7166
71 Features | Last Feature: mat_putz                            | F1-macro: 0.7166
72 Features | Last Feature: geom_z_min                          | F1-macro: 0.7166
73 Features | Last Feature: mat_foamglas                        | F1-macro: 0.7166

    n_features         last_feature_added  f1_macro
0            1           geom_layer_count    0.3796
1            2     topo_unique_edge_count    0.4801
2            3                  mat_belag    0.4890
3            4                   mat_gips    0.5092
4            5  topo_euler_characteristic    0.5600
..         ...                        ...       ...
68          69                 geom_z_max    0.7166
69          70                 mat_mörtel    0.7166
70          71                   mat_putz    0.7166
71          72                 geom_z_min    0.7166
72          73               mat_foamglas    0.7166

[73 rows x 3 columns]

## 4. Plot F1-macro vs. number of features

In [18]:
# plot the feature selection curve
# optimal top n features are 35
plot_feature_selection_curve(loop_df)