# Clean and seperate eBKPh code

## 1. Loading and preparing data

In [ ]:
# imports
import sys
from pathlib import Path
import plotly.graph_objects as go
import pandas as pd
import re

# helpers
sys.path.insert(0, "../../")
from _settings import SEED

In [2]:
# data directory and output path
DATA_MODELS_DIR = "../../1_data_mapping/1_2_data_mapping/mapped_data.parquet"
OUTPUT_PATH = "data_eBKPh_splitted.parquet"

# load parquet file
df = pd.read_parquet(DATA_MODELS_DIR)
df.head()

,ifc_file_path,model_name,ifc_schema,guid,ifc_entity,predefined_type_x,storey,type_gks,predefined_type_y,eBKPh,excel_label_file_path,excel_label_name,project_code
0,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1mvS9idiD3wBSng3jTXYT_,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
1,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1i$ZkNLnT42OfhsY2HRYEB,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
2,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,04t05b7LbESvNTIP4YWVjz,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
3,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,00tMo7QcxqWdIGvc4sMN2A,IfcBuilding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZUST
4,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3eYt9TfVT42ezAX4OpSOsQ,IfcBuildingStorey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZUST

In [3]:
df

,ifc_file_path,model_name,ifc_schema,guid,ifc_entity,predefined_type_x,storey,type_gks,predefined_type_y,eBKPh,excel_label_file_path,excel_label_name,project_code
0,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1mvS9idiD3wBSng3jTXYT_,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
1,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1i$ZkNLnT42OfhsY2HRYEB,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
2,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,04t05b7LbESvNTIP4YWVjz,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,NOTDEFINED,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
3,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,00tMo7QcxqWdIGvc4sMN2A,IfcBuilding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZUST
4,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3eYt9TfVT42ezAX4OpSOsQ,IfcBuildingStorey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZUST
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127422,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,3WjCdiWjDBQgNMTPRooJMm,IfcSpace,INTERNAL,10. Dachgeschoss,VF,INTERNAL,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/260202_nach_Aud...,ADEM_41_ARC_eBKPh_260202_labels,ADEM
127423,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,30dJ7acrD23hi5l7wHY2qF,IfcSpace,INTERNAL,9. Obergeschoss,FF,INTERNAL,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/260202_nach_Aud...,ADEM_41_ARC_eBKPh_260202_labels,ADEM
127424,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,1ApVC9mAn3jeKfhThRu9oz,IfcSpace,GFA,10. Dachgeschoss,GF,GFA,"[C Konstruktion Gebäude, C05 Ergänzende Leistu...",../../0_data/1_ifc_models/ADEM/260202_nach_Aud...,ADEM_41_ARC_eBKPh_260202_labels,ADEM
127425,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,3ypBL9h79BveiYOzmNg8c7,IfcSpace,INTERNAL,10. Dachgeschoss,FF,INTERNAL,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/260202_nach_Aud...,ADEM_41_ARC_eBKPh_260202_labels,ADEM
127426,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,0hNnaYzjHFTRJHO6j9rugt,IfcSpace,INTERNAL,10. Dachgeschoss,FF,INTERNAL,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/260202_nach_Aud...,ADEM_41_ARC_eBKPh_260202_labels,ADEM

In [4]:
len(df)

127427

## 2. Remove guid duplicates

In [5]:
# show duplicated guids
guid_counts = df["guid"].value_counts()
duplicated_guids = guid_counts[guid_counts > 1]
print(f"Count of deduplicated guids: {len(duplicated_guids)}")
print(duplicated_guids)

Count of deduplicated guids: 14147
guid
00tMo7QcxqWdIGvc4sMN2A    35
3eYt9TfVT42ezAX4OpSOsQ    35
3svIgCMrX8j8Gpr2WkHfaW    35
3NscPmsxv7yOs3PvwPDAMH    29
2FcQ$VfcDClOrgjBNOA$cL    28
                          ..
16P6CNrB52dBRkT6$pCi6W     2
30dJ7acrD23hi5l7wHY2qF     2
0hNnaYzjHFTRJHO6j9rugt     2
3WjCdiWjDBQgNMTPRooJMm     2
3ypBL9h79BveiYOzmNg8c7     2
Name: count, Length: 14147, dtype: int64

In [6]:
# remove duplicate guids (keep first occurrence per project_code)
df = df.drop_duplicates(subset=["project_code", "guid"], keep="first")
len(df)

108541

In [7]:
# show duplicated guids
guid_counts = df["guid"].value_counts()
duplicated_guids = guid_counts[guid_counts > 1]
print(f"Count of duplicated guids: {len(duplicated_guids)}")
print(duplicated_guids)

Count of duplicated guids: 13
guid
00tMo7QcxqWdIGvc4sMN2A    13
3eYt9TfVT42ezAX4OpSOsQ    13
3svIgCMrX8j8Gpr2WkHfaW    13
3NscPmsxv7yOs3PvwPDAMH    12
20FpTZCqJy2vhVJYtjuIce    12
2FcQ$VfcDClOrgjBNOA$cL    11
2K4L6BvTH3bejSwMgf$NzS     5
1wQ2fRh51CpANx1OonjEEm     4
210oJYMJH4C9Ac$CRKw6oW     4
1CmTYBxxD3gx6uetz_MQ2v     3
2cwoL2iFDDRBxh1WGc9zM0     3
05oAP5sYz0hw7opYcT2nYa     2
2x2coxbDH659_GFhhmTNX3     2
Name: count, dtype: int64

In [8]:
# check if guids are unique per project_code which in enough
duplicated = df[df.duplicated(subset=["project_code", "guid"], keep=False)]
print(f"Count of deduplicated guids for each project_code: {len(duplicated)}")
print(duplicated[["project_code", "guid"]].sort_values(["project_code", "guid"]))

Count of deduplicated guids for each project_code: 0
Empty DataFrame
Columns: [project_code, guid]
Index: []

## 3. Clean x and y values after merging

In [9]:
df.columns

Index(['ifc_file_path', 'model_name', 'ifc_schema', 'guid', 'ifc_entity',
       'predefined_type_x', 'storey', 'type_gks', 'predefined_type_y', 'eBKPh',
       'excel_label_file_path', 'excel_label_name', 'project_code'],
      dtype='str')

In [10]:
# analyse match between predefined_type_x and predefined_type_y
mask_both_present = df["predefined_type_x"].notna() & df["predefined_type_y"].notna()

df_both = df[mask_both_present].copy()
df_both["predefined_type_match"] = df_both["predefined_type_x"] == df_both["predefined_type_y"]

n_total    = len(df_both)
n_match    = df_both["predefined_type_match"].sum()
n_mismatch = n_total - n_match

print(f"Rows with both values present : {n_total}")
print(f"Match                         : {n_match}   ({n_match / n_total:.1%})")
print(f"Mismatch                      : {n_mismatch}   ({n_mismatch / n_total:.1%})")

Rows with both values present : 88442
Match                         : 88348   (99.9%)
Mismatch                      : 94   (0.1%)

In [11]:
# show mismatches
df_both[~df_both["predefined_type_match"]][["guid", "predefined_type_x", "predefined_type_y"]].tail(20)

                          guid predefined_type_x predefined_type_y
31962   3uNLq$lmnFRxHC9oeE3yQm          STRAIGHT        NOTDEFINED
31982   1aaEBj451CFvmgZEFERxKz          STRAIGHT        NOTDEFINED
31983   2v3FGGxjz86fXlb4w8oMzy          STRAIGHT        NOTDEFINED
32007   3p2auxj_X5sAOicHwfMlu1          STRAIGHT        NOTDEFINED
32008   1lzhwtvuX4I9epFl8UCr_b          STRAIGHT        NOTDEFINED
32009   1x31vPY0nDjA30IcgHnvzp          STRAIGHT        NOTDEFINED
32010   2AQN7rK2DCqhbpRJl3q7Gh          STRAIGHT        NOTDEFINED
32020   0Ve$Z9eifAOB0jtfQqsymP          STRAIGHT        NOTDEFINED
32021   1YMLZSStDABwJp6G9NXxcZ          STRAIGHT        NOTDEFINED
32522   3cdVQz8DnAcPzx8099p$f6        NOTDEFINED              BATH
82952   1d4abXeRy2F3zZuKIa7Utd          BASESLAB        NOTDEFINED
101283  3e7v2cNipNaCc8CMqxJrml          BASESLAB        NOTDEFINED
101291  1eVMrcIqRA4plhCFgd81Er             FLOOR        NOTDEFINED
101292  38$ImOwCbWoZLZVYNN4Yj9             FLOOR        NOTDEFINED
104814  2cHqmZwKj6r98_D8ATMnic           CEILING        INSULATION
104815  1FNxfHKRD6MxHryxtraHfz           CEILING        INSULATION
104816  0Ms2cRdXfEgfWnhJrC9vUZ           CEILING        INSULATION
104817  3AHct2w9fDRfcbYsSZa4T1           CEILING        INSULATION
104818  30tkm_f_fB7h9Mvw1Dk7$_           CEILING        INSULATION
104819  3C98QSc0rE3AF4GUuFuxgp           CEILING        INSULATION

In [12]:
# drop rows where differ betewen ifc model and label list
mask_mismatch = (
    df["predefined_type_x"].notna() &
    df["predefined_type_y"].notna() &
    (df["predefined_type_x"] != df["predefined_type_y"])
)
print(f"Dropping {mask_mismatch.sum()} mismatched rows")

df = df[~mask_mismatch].reset_index(drop=True)

Dropping 94 mismatched rows

## 4. rename ifc entity and predefined type

In [13]:
df = df.rename(columns={
    "ifc_entity": "label_ifc_entity",
    "predefined_type_x": "label_predefined_type",
})
df = df.drop(columns=["predefined_type_y"])
df

,ifc_file_path,model_name,ifc_schema,guid,label_ifc_entity,label_predefined_type,storey,type_gks,eBKPh,excel_label_file_path,excel_label_name,project_code
0,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1mvS9idiD3wBSng3jTXYT_,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
1,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1i$ZkNLnT42OfhsY2HRYEB,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
2,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,04t05b7LbESvNTIP4YWVjz,IfcBuildingElementProxy,NOTDEFINED,EG0,Pyramide 27,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,ZUST
3,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,00tMo7QcxqWdIGvc4sMN2A,IfcBuilding,NaN,NaN,NaN,NaN,NaN,NaN,ZUST
4,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3eYt9TfVT42ezAX4OpSOsQ,IfcBuildingStorey,NaN,NaN,NaN,NaN,NaN,NaN,ZUST
...,...,...,...,...,...,...,...,...,...,...,...,...
108442,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,1l9DLinKn3ygxxzj2uec_3,IfcSpace,EXTERNAL,9. Obergeschoss,AGF,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM
108443,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,0nwohU1qf14Rm3V5HUDWeH,IfcSpace,EXTERNAL,9. Obergeschoss,AGF,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM
108444,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,0e1EVFOyD26g9Z7qHNhG4S,IfcSpace,INTERNAL,9. Obergeschoss,HNF,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM
108445,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,3s82zmlxP4CRb7E$9YJbAM,IfcSpace,INTERNAL,9. Obergeschoss,HNF,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM
108446,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,2ss19PS$j60gcp9Pl39gDO,IfcSpace,GFA,9. Obergeschoss,GF,"[C Konstruktion Gebäude, C05 Ergänzende Leistu...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM

## 5. Split eBKPh code into own columns

In [14]:
# show all values
df["eBKPh"].value_counts()

eBKPh
Nicht klassifiziert                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   26367
[C02 Wandkonstruktion, C02.01 Aussenwandkonstruktion]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 10498
[E Äussere Wandbekleidung Gebäude, E02 Äussere Wandbekleidung über Terrain, E02.06 Aussen liegende Absturzsicherung]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   9552
[C02 Wandkonstruktion, C02.02 Innenwandkonstruktion]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8113
[F Bedachung Gebäude (A), F01 Dachhaut, F01.02 Bedachung Flachdach, F02 Element zu Dach (B), F02.03 Schutzanlage zu Dach]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              5500
[D04 Technische Brandschutzanlage (A), D05 Wärmetechnische Anlage (B)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 4595
[G01 Trennwand, Innentür, Innentor, G01.05 Innentür]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   3853
[G01 Trennwand, Innentür, Innentor, G01.03 Schachtfront]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3207
G05.05 Absturz-, Anprallschutzeinrichtung                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3028
[E Äussere Wandbekleidung Gebäude, E03 Element in Aussenwand, E03.01 Fenster]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3006
[D04 Technische Brandschutzanlage (A), D05 Wärmetechnische Anlage (B), G02 Bodenbelag (A), G02.02 Bodenbelag (A), G03 Wandbekleidung, G03.02 Wandbekleidung, G04 Deckenbekleidung (A), G04.02 Deckenbekleidung (A)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2025
[G01 Trennwand, Innentür, Innentor, G01.01 Fest stehende Trennwand]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1892
[D08 Wassertechnische Anlage (A), D08.05 Wasser: Armatur, Apparat]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1874
[C02 Wandkonstruktion, C02.01 Aussenwandkonstruktion, E Äussere Wandbekleidung Gebäude, E02 Äussere Wandbekleidung über Terrain, E02.03 Fassadenbekleidung]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1652
[C05.01 Durchbruch, Schlitz zu Konstruktion, G06.01 Durchbruch, Schlitz zu Ausbau]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1292
G01 Trennwand, Innentür, Innentor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1270
[E Äussere Wandbekleidung Gebäude, E03 Element in Aussenwand, E03.01 Fenster, E03.04 Sonnenschutz, Wetterschutz]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1211
[C04 Deckenkonstruktion, Dachkonstruktion, C04.08 Aussen liegende Konstruktion, Vordach]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1117
E03.05 Absturzsicherung                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1069

In [15]:
# define regex pattern and method for eBKPh codes
CODE_PATTERN = re.compile(r'\b[A-Z]\d{2}\.\d{2}|\b[A-Z]\d{2}|\b[A-Z](?=\s|$)')

# method to extract eBKPh codes from string, returns list of codes
def parse_eBKPh_codes(val):
    if pd.isna(val):
        return []
    return CODE_PATTERN.findall(str(val))

In [16]:
# apply method to create new columns for each code
df["eBKPh_original"] = df["eBKPh"]
df["eBKPh_parsed"] = df["eBKPh"].apply(parse_eBKPh_codes)
all_codes = sorted(set(code for codes in df["eBKPh_parsed"] for code in codes))

# create new columns for each code and set to True if code is present in the parsed list
for code in all_codes:
    col_name = f"eBKPh_{code.replace('.', '_')}"  # z.B. "ebkp_C2_1"
    df[col_name] = df["eBKPh_parsed"].apply(lambda codes: code in codes)

# drop the temporary parsed column
df.drop(columns=["eBKPh_parsed"], inplace=True)

print(df.head())
print(f"\nCreated columns: {[c for c in df.columns if c.startswith('eBKPh_') and c != 'eBKPh_original']}")

                                       ifc_file_path       model_name  \
0  ../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...  ZUST_P_ARC_VOL_
1  ../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...  ZUST_P_ARC_VOL_
2  ../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...  ZUST_P_ARC_VOL_
3  ../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...  ZUST_P_ARC_VOL_
4  ../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...  ZUST_P_ARC_VOL_

  ifc_schema                    guid         label_ifc_entity  \
0       IFC4  1mvS9idiD3wBSng3jTXYT_  IfcBuildingElementProxy
1       IFC4  1i$ZkNLnT42OfhsY2HRYEB  IfcBuildingElementProxy
2       IFC4  04t05b7LbESvNTIP4YWVjz  IfcBuildingElementProxy
3       IFC4  00tMo7QcxqWdIGvc4sMN2A              IfcBuilding
4       IFC4  3eYt9TfVT42ezAX4OpSOsQ        IfcBuildingStorey

  label_predefined_type storey     type_gks                eBKPh  \
0            NOTDEFINED    EG0  Pyramide 27  Nicht klassifiziert
1            NOTDEFINED    EG0  Pyramide 27  Nicht klassifiziert
2            NOTDEFINED    EG0  Pyramide 27  Nicht klassifiziert
3                   NaN    NaN          NaN                  NaN
4                   NaN    NaN          NaN                  NaN

                               excel_label_file_path  ... eBKPh_G05  \
0  ../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...  ...     False
1  ../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...  ...     False
2  ../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...  ...     False
3                                                NaN  ...     False
4                                                NaN  ...     False

  eBKPh_G05_01 eBKPh_G05_02  eBKPh_G05_05  eBKPh_G05_06  eBKPh_G05_07  \
0        False        False         False         False         False
1        False        False         False         False         False
2        False        False         False         False         False
3        False        False         False         False         False
4        False        False         False         False         False

   eBKPh_G06  eBKPh_G06_01  eBKPh_G06_03  eBKPh_G06_04
0      False         False         False         False
1      False         False         False         False
2      False         False         False         False
3      False         False         False         False
4      False         False         False         False

[5 rows x 110 columns]

Created columns: ['eBKPh_C', 'eBKPh_C01', 'eBKPh_C01_01', 'eBKPh_C01_02', 'eBKPh_C01_03', 'eBKPh_C02', 'eBKPh_C02_01', 'eBKPh_C02_02', 'eBKPh_C03', 'eBKPh_C03_01', 'eBKPh_C03_02', 'eBKPh_C04', 'eBKPh_C04_01', 'eBKPh_C04_02', 'eBKPh_C04_03', 'eBKPh_C04_04', 'eBKPh_C04_05', 'eBKPh_C04_06', 'eBKPh_C04_08', 'eBKPh_C05', 'eBKPh_C05_01', 'eBKPh_C05_02', 'eBKPh_D', 'eBKPh_D01', 'eBKPh_D01_01', 'eBKPh_D01_02', 'eBKPh_D01_03', 'eBKPh_D01_04', 'eBKPh_D01_05', 'eBKPh_D01_06', 'eBKPh_D01_07', 'eBKPh_D01_08', 'eBKPh_D01_09', 'eBKPh_D01_10', 'eBKPh_D01_11', 'eBKPh_D02', 'eBKPh_D03', 'eBKPh_D04', 'eBKPh_D05', 'eBKPh_D06', 'eBKPh_D07', 'eBKPh_D08', 'eBKPh_D08_05', 'eBKPh_D09', 'eBKPh_D10', 'eBKPh_D11', 'eBKPh_D12', 'eBKPh_D12_01', 'eBKPh_E', 'eBKPh_E01', 'eBKPh_E01_01', 'eBKPh_E01_02', 'eBKPh_E01_03', 'eBKPh_E02', 'eBKPh_E02_01', 'eBKPh_E02_02', 'eBKPh_E02_03', 'eBKPh_E02_06', 'eBKPh_E03', 'eBKPh_E03_01', 'eBKPh_E03_02', 'eBKPh_E03_03', 'eBKPh_E03_04', 'eBKPh_E03_05', 'eBKPh_F', 'eBKPh_F01', 'eBKPh_F01_02', 'eBKPh_F02', 'eBKPh_F02_01', 'eBKPh_F02_02', 'eBKPh_F02_03', 'eBKPh_G', 'eBKPh_G01', 'eBKPh_G01_01', 'eBKPh_G01_02', 'eBKPh_G01_03', 'eBKPh_G01_04', 'eBKPh_G01_05', 'eBKPh_G01_06', 'eBKPh_G02', 'eBKPh_G02_01', 'eBKPh_G02_02', 'eBKPh_G03', 'eBKPh_G03_02', 'eBKPh_G04', 'eBKPh_G04_01', 'eBKPh_G04_02', 'eBKPh_G05', 'eBKPh_G05_01', 'eBKPh_G05_02', 'eBKPh_G05_05', 'eBKPh_G05_06', 'eBKPh_G05_07', 'eBKPh_G06', 'eBKPh_G06_01', 'eBKPh_G06_03', 'eBKPh_G06_04']

In [17]:
df.columns

Index(['ifc_file_path', 'model_name', 'ifc_schema', 'guid', 'label_ifc_entity',
       'label_predefined_type', 'storey', 'type_gks', 'eBKPh',
       'excel_label_file_path',
       ...
       'eBKPh_G05', 'eBKPh_G05_01', 'eBKPh_G05_02', 'eBKPh_G05_05',
       'eBKPh_G05_06', 'eBKPh_G05_07', 'eBKPh_G06', 'eBKPh_G06_01',
       'eBKPh_G06_03', 'eBKPh_G06_04'],
      dtype='str', length=110)

In [ ]:
# save example as csv for documentation
cols = ['project_code', 'eBKPh_original'] + [c for c in df.columns if c.startswith('eBKPh_') and c != 'eBKPh_original']
df[cols].sample(50, random_state=SEED).to_csv("eBKPh_splitting_sample.csv", index=False)

## 6. Enrich the main codes from their subcodes

In [19]:
# propagate subcodes to parent codes for a hierarchical consistency
for col in [c for c in df.columns if c.startswith('eBKPh_') and c not in ('eBKPh_original', 'eBKPh_status')]:
    code = col.replace('eBKPh_', '').replace('_', '.')

    if re.match(r'^[A-Z]\d{2}\.\d{2}$', code):           # four_digit: C02.01
        parent_two    = f"eBKPh_{code[:3]}"              # -> C02
        parent_letter = f"eBKPh_{code[0]}"               # -> C
        if parent_two in df.columns:
            df[parent_two] = df[parent_two] | df[col]
        if parent_letter in df.columns:
            df[parent_letter] = df[parent_letter] | df[col]

    elif re.match(r'^[A-Z]\d{2}$', code):                # two_digit: C02
        parent_letter = f"eBKPh_{code[0]}"               # -> C
        if parent_letter in df.columns:
            df[parent_letter] = df[parent_letter] | df[col]

In [20]:
# save as parquet
df.to_parquet(OUTPUT_PATH, index=False)
print(f"DataFrame with {len(df)} rows and {len(df.columns)} columns were saved as: '{OUTPUT_PATH}'")

DataFrame with 108447 rows and 110 columns were saved as: 'data_eBKPh_splitted.parquet'