# Analyse best runs in the hyperparameter process

In [ ]:
import pandas as pd

# TODO: Change to new feolder and use wandb for taking metrics
# TODO: Add also csv with best runs to see it for laters

## 1. Hyperparameter tuning for Random Forest

In [13]:
# load existing results from the hyperparameter tuning process
results_csv_rf = "rf_grid_search_results.csv"
existing_df = pd.read_csv(results_csv_rf)

# show best twenty results
existing_df.sort_values("f1_macro_score", ascending=False).head(30)

,bootstrap,max_depth,min_samples_leaf,min_samples_split,n_estimators,f1_macro_score
1611,False,NaN,1,2,1500,0.9603
1609,False,NaN,1,2,1200,0.9603
1610,False,NaN,1,2,1400,0.9602
1608,False,NaN,1,2,1000,0.9598
1607,False,NaN,1,2,750,0.9596
1600,False,NaN,1,2,250,0.9595
1604,False,NaN,1,2,450,0.9594
1603,False,NaN,1,2,400,0.9594
1602,False,NaN,1,2,350,0.9594
977,False,200.0,1,2,200,0.9592
602,False,NaN,1,2,200,0.9592
1601,False,NaN,1,2,300,0.9592
902,False,150.0,1,2,200,0.9592
827,False,100.0,1,2,200,0.9592
1052,False,250.0,1,2,200,0.9592
1127,False,300.0,1,2,200,0.9592
752,False,50.0,1,2,200,0.9592
1450,False,50.0,1,2,150,0.9591
1475,False,100.0,1,2,150,0.9591
1500,False,150.0,1,2,150,0.9591
1525,False,200.0,1,2,150,0.9591
1400,False,NaN,1,2,150,0.9591
1550,False,250.0,1,2,150,0.9591
1605,False,NaN,1,2,500,0.9591
1575,False,300.0,1,2,150,0.9591
1606,False,NaN,1,2,600,0.9590
1051,False,250.0,1,2,100,0.9588
976,False,200.0,1,2,100,0.9588
751,False,50.0,1,2,100,0.9588
601,False,NaN,1,2,100,0.9588

## 2. Hyperparameter tuning for XGBoost

In [14]:
# load existing results from the hyperparameter tuning process
results_csv_rf = "xgboost_hyperopt_results.csv"
existing_df = pd.read_csv(results_csv_rf)

# show best twenty results
existing_df.sort_values("f1_macro_score", ascending=False).head(20)

,colsample_bylevel,colsample_bytree,gamma,learning_rate,max_depth,min_child_weight,n_estimators,reg_alpha,reg_lambda,subsample,f1_macro_score
301,0.772713,0.580679,0.008083,0.040281,9,5,1250,0.012954,0.207787,0.920144,0.9553
285,0.803427,0.914025,0.107827,0.083648,9,3,1250,0.030058,0.060758,0.944998,0.9552
372,0.959086,0.591527,0.007456,0.162901,6,2,750,0.114436,0.889545,0.579658,0.9552
284,0.805117,0.999295,0.105038,0.082467,9,3,1250,0.219499,0.028386,0.989993,0.9551
309,0.655665,0.579482,0.005809,0.063579,6,2,1000,0.439711,0.926935,0.775893,0.9550
282,0.830648,0.999265,0.071238,0.072266,9,3,1250,0.033896,0.244348,0.990359,0.9549
287,0.753473,0.906502,0.086556,0.097558,9,3,1250,0.002549,0.389992,0.935373,0.9549
253,0.626666,0.748897,0.015833,0.089032,9,2,500,0.190183,4.228631,0.705842,0.9548
386,0.843551,0.592353,0.053866,0.115968,9,2,1500,0.370555,2.417539,0.869116,0.9548
374,0.999911,0.591473,0.008271,0.289972,6,2,750,0.123026,2.611062,0.872137,0.9548
283,0.825671,0.973577,0.088799,0.072833,9,3,1250,0.042754,0.023518,0.998367,0.9546
237,0.547161,0.697510,0.029766,0.087288,9,7,1000,0.031533,2.375494,0.838136,0.9544
322,0.679809,0.949491,0.051984,0.092516,7,0,1250,0.253628,1.882478,0.970873,0.9543
375,0.914931,0.588358,0.008244,0.282596,6,2,750,0.106373,2.513057,0.898197,0.9542
319,0.578465,0.615887,0.030277,0.200099,8,1,1500,0.520056,3.677519,0.789118,0.9539
336,0.588363,0.723223,0.005462,0.041461,9,3,1500,0.650177,3.069344,0.603178,0.9539
238,0.548958,0.918192,0.026863,0.071521,8,8,1000,0.593746,2.271253,0.848220,0.9538
345,0.627481,0.848176,0.016410,0.041917,7,3,1250,0.117507,4.080697,0.565101,0.9538
392,0.756772,0.586016,0.023125,0.210192,10,3,1000,0.044289,0.147174,0.713245,0.9537
181,0.937643,0.676038,0.006980,0.126035,9,6,500,0.569743,0.862065,0.815646,0.9536